services:
  - type: web
    name: raspadinha
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 8000
